language: cpp
dist: trusty
sudo: required
compiler: gcc
before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt571-trusty -y
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
script:
 - qmake -v
 - qmake -r
 - cd tests/
 - qmake -project
 - qmake tests/qtcreator-experements-tests.pro
 - make
 - ls -R
 - ./qtcreator-experements-tests
 - make clean
 - cd ..
 - make -project
 - qmake qtcreator-experements.pro
 - make
